### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by s-weigand**
Based on the docs of glotaran, i generated docs for ``lmfit-varpro`` here is a preview
[docs_preview.zip](https://github.com/glotaran/lmfit-varpro/files/2176193/docs_preview.zip).

When this PR is merged, the rtd link (introduce by this PR) should show the proper docs.

### CODE REVIEW

**Comment by s-weigand** [comment]
Again ignore the CI, since its not configured yet.
This will be the next step.

**Comment by joernweissenborn** [comment]
Could you give a short overview of what exactly you did?

**Comment by s-weigand** [comment]
Basically i used the same cookiecutter template as for the glotaran docs [#80](https://github.com/glotaran/glotaran/pull/80) and changed the structure and and additional information acording to the docs i wrote for glotaran.

**Comment by joernweissenborn** [comment]
closes #9

**Pull request merged**
